data:
  image_root: "/content/drive/MyDrive/deepfashion/data/raw/images"
  train_csv: "/content/drive/MyDrive/deepfashion/data/processed/train.csv"
  val_csv: "/content/drive/MyDrive/deepfashion/data/processed/val.csv"

training:
  batch_size: 64
  epochs: 10
  lr: 0.0001
  save_path: "/content/drive/MyDrive/deepfashion/checkpoints/resnet50_attr_finetune.pth"
